langthil/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^w/', include('wiki.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='wiki-start')),
]

wiki/urls.py
from django.urls import path,register_converter


from wiki.pages import WikiStart
from wiki import views


class NamespaceConverter:
    regex = r'(?:[-a-zA-Z0-9_()]+/)*'

    def to_python(self, value):
        return str(value).strip('/')

    def to_url(self, value):
        value = str(value).strip('/')

        if value:
            return value + '/'

        return ''
register_converter(NamespaceConverter, 'namespace')

class WikiSlugConverter:
    regex = r'[-a-zA-Z0-9_()]+'

    def to_python(self, value):
        return str(value)

    def to_url(self, value):
        return str(value)
register_converter(WikiSlugConverter, 'wikislug')


urlpatterns = [
    path('glossary', views.GlossaryView.as_view(), name='wiki-glossary'),
    path('glossary;action=edit', views.TermCreateView.as_view(), name='wiki-term-new'),
    path('glossary;action=edit&term=<int:pk>', views.TermEditView.as_view(), name='wiki-term-edit'),

    path('special:index', views.ArticleListView.as_view(), name='wiki-index'),
    path('special:preview', views.PreviewView.as_view(), name='wiki-preview'),

    path('tag:<wikislug:slug>', views.TagView.as_view(), name='wiki-tag'),
    path('tag:<wikislug:slug>;action=edit', views.TagEditView.as_view(), name='wiki-tag-edit'),

    path('<namespace:namespace><wikislug:slug>;action=create', views.WikiCreateView.as_view(), name='wiki-new'),
    path('<namespace:namespace><wikislug:slug>;action=edit', views.WikiUpdateView.as_view(), name='wiki-edit'),
    path('<namespace:namespace><wikislug:slug>;action=move', views.WikiMoveView.as_view(), name='wiki-move'),
    path('<namespace:namespace><wikislug:slug>', views.WikiPageView.as_view(), name='wiki'),
    path('', views.WikiPageView.as_view(), kwargs=WikiStart, name='wiki-start'),
]

worldwiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^w/', include('wiki.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='wiki-start')),
]

wiki/models.py
import re
from urllib.parse import parse_qsl,urlencode,urlsplit,urlunsplit


from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse, NoReverseMatch
from django.utils import timezone
from django.utils.safestring import mark_safe


from wiki import utils
from wiki.fields import WikiSlugField,WikiNamespaceField
from wiki.markdown import Markdown


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = WikiSlugField(unique=True, blank=True)
    description = models.TextField('tag description', help_text='Formatted using Markdown', blank=True)

    @property
    def html(self):
        html = Markdown.to_html(self.description)
        return mark_safe(html)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = utils.slugify(self.name)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('wiki-tag', args=(self.slug,))

    class Meta:
        ordering = ('name',)


class Article(models.Model):
    title = models.CharField('article title', max_length=50)
    namespace = WikiNamespaceField(blank=True, default='')
    slug = WikiSlugField(blank=True)
    published = models.DateTimeField(null=True, default=None)
    edited = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('publish?', default=False)
    is_nsfw = models.BooleanField('NSFW?', default=False)
    is_spoiler = models.BooleanField('spoiler?', default=False)
    tags = models.ManyToManyField(
            Tag,
            related_name='articles',
            related_query_name='article',
            blank=True,
            )
    markdown = models.TextField('article content', help_text='Formatted using Markdown')

    @property
    def html(self):
        meta = {
            'title': self.title,
            'published': self.published,
            'namespace': self.namespace,
        }

        html = Markdown.to_html(self.markdown, meta)
        return mark_safe(html)

    REDIRECT_RE = re.compile(r'^\[\[REDIRECT:(?P<redirect>.*?)\]\]', re.I)

    @property
    def is_redirect(self):
        return self.REDIRECT_RE.match(self.markdown.strip()) is not None

    def get_redirect(self, qs=None):
        m = self.REDIRECT_RE.match(self.markdown.strip())

        if m is None:
            return None

        url = m.group('redirect')
        # Prepend current namespace if redirect URL is not absolute
        url = utils.join_path(self.namespace, url)

        # Get and slugify namespace and slug from URL
        namespace, slug = utils.split_path(url)
        slug = utils.slugify(slug)
        namespace = utils.slugify_namespace(namespace)

        if qs is None:
            qs = Article.objects.filter(is_published=True)

        return qs.get(namespace=namespace, slug=slug)

    def _sticky_url(self, url):
        url = urlsplit(url)

        query = parse_qsl(url.query)
        query.append(('redirect','no'))

        url = url._replace(query=urlencode(query))

        return urlunsplit(url)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = utils.slugify(self.title)

        if self.slug.startswith('special:'):
            self.is_published = True
            self.is_nsfw = False
            self.is_spoiler = False

        self.validate_unique()

        if self.is_published and not self.published:
            self.published = timezone.now()

        return super().save(*args, **kwargs)

    def clean(self):
        super().clean()

        if not self.slug:
            self.slug = utils.slugify(self.title)

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude)

        qs = Article.objects.filter(slug=self.slug, namespace=self.namespace)
        if self.pk:
            qs = qs.exclude(pk=self.pk)

        if qs.exists():
            raise ValidationError({'slug':'Namespace+slug must be unique (case-insensitive)'})

    def get_absolute_url(self):
        return self.__reverse('wiki')

    def get_edit_url(self):
        return self.__reverse('wiki-edit')

    def get_move_url(self):
        return self.__reverse('wiki-move')

    def __reverse(self, url):
        try:
            return reverse(url, args=[self.namespace, self.slug])
        except NoReverseMatch:
            return None

    def get_admin_url(self):
        return reverse('admin:wiki_article_change', args=(self.pk,))

    class Meta:
        ordering = ('slug',)


class Term(models.Model):
    term = models.CharField(max_length=250, unique=True)
    definition = models.TextField()

    @property
    def anchor(self):
        return utils.slugify(self.term)

    def get_absolute_url(self):
        return '{url}#{anchor}'.format(
            url = reverse('wiki-glossary'),
            anchor = self.anchor,
        )

    class Meta:
        ordering = ('term',)

wiki/forms.py
from django.forms import ModelForm,CharField


from wiki.models import Article,Tag


class TaggableArticleMixin(ModelForm):
    tag_list = CharField(
        required=False,
        max_length=1024,
        label='Tags',
        help_text='Multiple tags may be separated by commas',
    )

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        if instance:
            tags = ', '.join([tag.name for tag in instance.tags.all()])
            if tags:
                initial = kwargs.get('initial', {})
                initial['tag_list'] = tags
                kwargs['initial'] = initial

        return super().__init__(*args, **kwargs)

    def _save_tags(self):
        tags = self.cleaned_data['tag_list'].split(',')
        objs = []

        for tag in tags:
            tag = tag.strip()
            if not tag:
                continue

            obj, created = Tag.objects.get_or_create(
                name__iexact=tag,
                defaults={'name':tag},
            )
            objs.append(obj)

        if objs:
            self.instance.tags.set(objs)

    def save(self, commit=True):
        # TODO: If commit is True, postpone saving tags until save_m2m() called
        # In the meantime, that function is not implemented
        if not commit:
            raise NotImplementedError()

        obj = super().save(commit)

        self._save_tags()

        return obj


class ArticleCreateForm(TaggableArticleMixin, ModelForm):
    class Meta:
        model = Article
        fields = ('title','namespace','slug','tag_list','markdown','is_published','is_nsfw','is_spoiler')


class ArticleUpdateForm(TaggableArticleMixin, ModelForm):
    class Meta:
        model = Article
        fields = ('title','tag_list','markdown','is_published','is_nsfw','is_spoiler')

wiki/views.py
from django.http import Http404,HttpResponse
from django.shortcuts import get_object_or_404,redirect,render
from django.urls import reverse,reverse_lazy
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic import DetailView,ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView


from wiki import forms
from wiki import utils
from wiki.markdown import Markdown
from wiki.models import Article,Tag,Term
from wiki.pages import Error404


# Create your views here.

class TagView(DetailView):
    model = Tag
    context_object_name = 'tag'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        articles = []
        for article in self.object.articles.all():
            if not article.is_redirect:
                articles.append(article)

        context['articles'] = articles

        return context

class TagEditView(UpdateView):
    model = Tag
    context_object_name = 'tag'
    fields = ('name','slug','description')


class ArticleListView(ListView):
    queryset = Article.objects.filter(is_published=True).exclude(slug__startswith='special:')
    context_object_name = 'articles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = 'All Pages on Langthil'

        return context


class WikiPageView(View):
    article_template = 'wiki/article_detail.html'
    nsfw_template = 'wiki/article_nsfw.html'
    disambiguation_template = 'wiki/article_list.html'
    show_nsfw_content = False
    create_url = None

    def get(self, request, slug, namespace):
        self.show_nsfw_content = self.show_nsfw_content or request.session.get('show_nsfw', False)

        try:
            redirected, article = self.get_article(slug, namespace)
            context = {
                'article':article,
                'redirected':redirected,
                'canonical_url':article.get_absolute_url(),
            }
        except Article.DoesNotExist:
            article = Error404.get()
            context = {
                'article':article,
                'create_url':reverse('wiki-new', args=[namespace, slug]),
            }

        if article.is_nsfw and not self.show_nsfw_content:
            return render(request, self.nsfw_template, context=context)
        else:
            return render(request, self.article_template, context=context)

    def post(self, request, *args, **kwargs):
        if request.POST.get('show-me'):
            self.show_nsfw_content = True
            if request.POST.get('remember'):
                request.session['show_nsfw'] = True

        return self.get(request, *args, **kwargs)

    def get_article(self, slug, namespace):
        if self.request.user.has_perm('wiki.change_article') or 'preview' in self.request.GET:
            qs = Article.objects
        else:
            qs = Article.objects.filter(is_published=True)

        article = qs.get(slug=slug, namespace=namespace)

        if article.is_redirect and self.request.GET.get('redirect') != 'no':
            try:
                return (article, article.get_redirect(qs))
            except Article.DoesNotExist:
                pass

        return (None, article)


class WikiUpdateView(UpdateView):
    model = Article
    form_class = forms.ArticleUpdateForm

    def get_object(self, queryset=None):
        queryset = queryset or self.get_queryset()

        return queryset.get(**self.kwargs)

class WikiCreateView(CreateView):
    model = Article
    form_class = forms.ArticleCreateForm

    def get_initial(self):
        slug = self.kwargs['slug']
        title = slug.replace('_', ' ').strip().title()

        if not self.kwargs['slug'].startswith('_'):
            slug = utils.slugify(title)

        initial = {
            'title': title,
            'slug': slug,
            'namespace': self.kwargs['namespace'],
            'is_published': True,
        }

        template = self._get_template()
        if template:
            initial['markdown'] = template

        return initial

    def _get_template(self):
        # Start with a bogus "extra" namespace
        # We'll pop it off before the first lookup, which is how we'll get to the root
        namespace = utils.join_path(self.kwargs['namespace'], '__extra__')

        while namespace:
            namespace = utils.namespace(namespace)

            try:
                tmpl = Article.objects.get(namespace=namespace, slug='_template')
                return tmpl.markdown
            except Article.DoesNotExist:
                pass

        return None

class WikiMoveView(WikiUpdateView):
    form_class = None
    fields = ('namespace','slug')

    def form_valid(self, form):
        response = super().form_valid(form)

        self.__create_redirect_page()

        return response

    def __create_redirect_page(self):
        # Verify we're changing more than case
        if self.kwargs['namespace'].lower() == self.object.namespace.lower():
            if self.kwargs['slug'].lower() == self.object.slug.lower():
                return

        redirect = Article(
            title = self.object.title,
            is_published = self.object.is_published,
            is_nsfw = self.object.is_nsfw,
            is_spoiler = self.object.is_spoiler,
            **self.kwargs,
        )
        redirect.markdown = '[[REDIRECT:/{article}]]'.format(
            article = utils.join_path(self.object.namespace, self.object.slug),
        )
        redirect.save()

class PreviewView(View):
    def post(self, request):
        return HttpResponse(Markdown.to_html(request.POST.get('markdown', '')))


class GlossaryView(ListView):
    model = Term
    context_object_name = 'terms'

class TermCreateView(CreateView):
    model = Term
    fields = ('term', 'definition')

class TermEditView(UpdateView):
    model = Term
    fields = ('term', 'definition')

wiki/templates/wiki/_base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		{% load static %}
		<title>{% block title %}Welcome{% endblock %}{% if wiki.title %} &mdash; {{ wiki.title }}{% endif %}</title>

		<!-- Bootstrap -->
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/bootstrap-theme.min.css" rel="stylesheet">
		<link href="{% static 'wiki/wiki.css' %}" rel="stylesheet">
		{% block styles %}{% endblock %}

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<header id="top">
			<a href="{% url 'wiki-start' %}">{{ wiki.title | default:'WorldWiki' }}</a>
		</header>

		<div class="container">
			<div class="content">
				<h1>{% block header %}Welcome{% endblock %}</h1>

				{% block content %}Hello, world!{% endblock content %}
			</div>

			<div class="sidebar">{{ wiki.sidebar.content }}</div>
		</div>

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="/js/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="/js/bootstrap.min.js"></script>
		<script src="{% static 'wiki/wiki.js' %}"></script>
		{% block scripts %}{% endblock %}
	</body>
</html>

wiki/templates/wiki/article_detail.html
{% extends 'wiki/_base.html' %}

{% block title %}{{ article.title }}{% endblock %}
{% block header %}{{ article.title }}{% endblock %}

{% block content %}
<div
	id="article_tags"
	data-canonical="{{ canonical_url }}"
	class="articles-tags text-right">
	{% if not article.is_published %}<span class="label label-warning">Unpublished</span>{% endif %}
	{% if article.is_redirect %}<span class="label label-warning">Redirect Page</span>{% endif %}
	{% if article.is_nsfw %}<span class="label label-danger">NSFW</span>{% endif %}
	{% if article.is_spoiler %}<span class="label label-warning">Spoiler</span>{% endif %}
	{% for tag in article.tags.all %}
	<a href="{% url 'wiki-tag' slug=tag.slug %}" class="label label-info">{{ tag }}</a>
	{% endfor %}
	{% if perms.wiki.change_article %}
	{% if create_url %}
	<a href="{{ create_url }}" class="btn btn-xs btn-default" id="new-page">New</a>
	{% else %}
	<div class="btn-group">
		<a href="{{ article.get_edit_url }}" class="btn btn-xs btn-default" id="edit-page">Edit</a>
		<a href="{{ article.get_move_url }}" class="btn btn-xs btn-default" id="move-page">Move</a>
	</div>
	{% endif %}
	{% endif %}
</div>
<div class="article_content">
	<div>
		{% if redirected %}
		<p class="hatnote">
		Redirected from <a href="{{ redirected.get_absolute_url }}?redirect=no">{{ redirected.title }}</a>
		</p>
		{% endif %}
		{{ article.html }}
	</div>
	<button role="button" class="btn btn-xs btn-default pull-right" id="show-source">View Source</button>
</div>

<div class="article_source">
	<div>{{ article.markdown }}</div>
	<button role="button" class="btn btn-xs btn-default pull-right" id="hide-source">Hide Source</button>
</div>

<div id="article_edited">
	Last modified on {{ article.edited | date }}
</div>
{% endblock content %}

wiki/templates/wiki/article_form.html
{% extends 'wiki/_base.html' %}
{% load static %}

{% block title %}Editing: {{ article.title }}{% endblock %}
{% block header %}Editing: {{ article.title }}{% endblock %}

{% block content %}
<div class="articles-tags text-right">
	{% if not article.is_published %}<span class="label label-warning">Unpublished</span>{% endif %}
	{% if article.is_nsfw %}<span class="label label-danger">NSFW</span>{% endif %}
	{% if article.is_spoiler %}<span class="label label-warning">Spoiler</span>{% endif %}
	{% if article.pk %}
	{% for tag in article.tags.all %}
	<a href="{% url 'wiki-tag' slug=tag.slug %}" class="label label-info">{{ tag }}</a>
	{% endfor %}
	{% endif %}
	<button role="button" id="go-back" class="btn btn-xs btn-default">Cancel</button>
</div>
<div class="article_edit">
	{% if form.instance.slug %}
	<em>
		Editing page at
		"{% if form.instance.namespace %}{{ form.instance.namespace }}/{% endif %}{{ form.instance.slug }}"
	</em>
	{% endif %}
	<form method="POST" id="article-form">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="text-right">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</form>
</div>

<div id="article_edited">
	Last modified on {{ article.edited }}
</div>
{% endblock content %}

{% block styles %}
<link href="{% static 'wiki/bootstrap-markdown.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'wiki/jquery.hotkeys.js' %}"></script>
<script src="{% static 'wiki/bootstrap-markdown.js' %}"></script>
{% endblock %}

wiki/templates/wiki/article_nsfw.html
{% extends 'wiki/_base.html' %}

{% block title %}This Content May Be NSFW{% endblock %}
{% block header %}This Content May Be NSFW{% endblock %}

{% block content %}
<div class="article_content article_nsfw">
	<h2>Potentially graphic or offensive content</h2>

	<p>
	The content at "{{ article.title }}" has been flagged by the author
	as being potentially
	<abbr title="Not Safe For Work" class="initialism">NSFW</abbr>.
	This could be because the content is sexually explicit, violent,
	or otherwise offensive or disturbing to some readers.
	</p>

	<p>
	<strong>Nothing on this site is pornographic.</strong> Violent,
	sexual, and otherwise "offensive" content exists in the world of
	Langthil for many of the same reasons as they do in the real
	world. Langthil doesn't sweep these issues under the rug and
	pretend they don't exist, and neither does it seek to minimize or
	downplay them.
	</p>

	<p>
	<form method="post">
		<div class="checkbox">
			<label>
				<input type="checkbox" name="show-me" value="true">
				I understand and wish to continue
			</label>
		</div>
		<div class="checkbox">
			<label>
				<input type="checkbox" name="remember" value="true">
				Remember my choice for the rest of my browser session
			</label>
		</div>
		{% csrf_token %}
		<button type="button" class="btn btn-success" id="go-back">Go Back</button>
		<button type="submit" class="btn btn-warning" id="forward">Proceed</button>
	</form>
	</p>
</div>
{% endblock content %}

wiki/templates/wiki/edit.html
{% extends 'wiki/_base.html' %}
{% load static %}

{% block title %}Editing: {{ article.title }}{% endblock %}
{% block header %}Editing: {{ article.title }}{% endblock %}

{% block content %}
<div class="articles-tags text-right">
	{% if not article.is_published %}<span class="label label-warning">Unpublished</span>{% endif %}
	{% if article.is_nsfw %}<span class="label label-danger">NSFW</span>{% endif %}
	{% if article.is_spoiler %}<span class="label label-warning">Spoiler</span>{% endif %}
	{% if article.pk %}
	{% for tag in article.tags.all %}
	<a href="{% url 'wiki-tag' slug=tag.slug %}" class="label label-info">{{ tag }}</a>
	{% endfor %}
	{% endif %}
	<button role="button" id="go-back" class="btn btn-xs btn-default">Cancel</button>
</div>
<div class="article_edit">
	<form method="POST" id="article-form">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="text-right">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</form>
</div>

<div id="article_edited">
	Last modified on {{ article.edited }}
</div>
{% endblock content %}

{% block styles %}
<link href="{% static 'wiki/bootstrap-markdown.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'wiki/jquery.hotkeys.js' %}"></script>
<script src="{% static 'wiki/bootstrap-markdown.js' %}"></script>
{% endblock %}

wiki/templates/wiki/page_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="page_content">
	<div>
		{{ page.as_html }}
	</div>
	<button class="btn btn-xs btn-primary" id="show-source">View Source</button>
</div>

<div class="page_source">
	<div>
		{{ page.body }}
	</div>
	<button class="btn btn-xs btn-primary" id="hide-source">Hide Source</button>
</div>
{% endblock content %}

{% block styles %}
<link href="{% static 'wiki/wiki.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'wiki/wiki.js' %}"></script>
{% endblock %}

wiki/templates/wiki/tag_detail.html
{% extends 'wiki/_base.html' %}

{% block title %}Tag:{{ tag.name }}{% endblock %}
{% block header %}Tag:{{ tag.name }}{% endblock %}

{% block content %}
{% if perms.wiki.change_tag %}
<div class="text-right">
	<div class="btn-group">
		<a href="{% url 'wiki-tag-edit' tag.slug %}" class="btn btn-xs btn-default" id="edit-page">Edit</a>
	</div>
</div>
{% endif %}
<div class="tag-description">{{ tag.html }}</div>
<div class="tag-articles">
	<p class="hatnote">
		There {{ articles|pluralize:"is,are" }} {{ articles|length }}
		article{{ articles|pluralize }} tagged {{ tag.name }}
	</p>
	<div class="row">
		{% for article in articles %}
		<div class="col-lg-4 col-sm-6"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

wiki/templates/wiki/tag_form.html
{% extends 'wiki/_base.html' %}
{% load static %}

{% block title %}Editing Tag: {{ tag.name }}{% endblock %}
{% block header %}Editing Tag: {{ tag.name }}{% endblock %}

{% block content %}
<div class="tag_edit">
	<form method="POST" id="tag-form">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="text-right">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</form>
</div>
{% endblock content %}

{% block styles %}
<link href="{% static 'wiki/bootstrap-markdown.min.css' %}" rel="stylesheet">
{% endblock %}

{% block scripts %}
<script src="{% static 'wiki/jquery.hotkeys.js' %}"></script>
<script src="{% static 'wiki/bootstrap-markdown.js' %}"></script>
{% endblock %}

wiki/templates/wiki/term_form.html
{% extends 'wiki/_base.html' %}

{% block title %}Glossary{% endblock %}
{% block header %}Glossary{% endblock %}

{% block content %}
<div class="term_edit">
	<form method="POST" id="term-form">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="text-right">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</form>
</div>
{% endblock %}

wiki/templates/wiki/term_list.html
{% extends 'wiki/_base.html' %}

{% block title %}Glossary{% endblock %}
{% block header %}Glossary{% endblock %}

{% block content %}
<div class="term-list">
	{% regroup terms by term.0|upper as glossary %}
	{% if perms.wiki.add_term %}
	<a href="{% url 'wiki-term-new' %}" class="btn btn-xs btn-success">New Term</a>
	{% endif %}

	<ul class="index">
		<li>Jump to:</li>
		{% for index, terms in glossary %}
		<li><a href="#{{ index }}">{{ index }}</a></li>
		{% endfor %}
	</ul>

	{% for index, terms in glossary %}
	<h2 id="{{ index }}">{{ index }} <a class="subhead" href="#top">back to top</a></h2>
	<dl>
		{% for term in terms %}
		<div id="{{ term.anchor }}">
			<dt>
				{{ term.term }}
				{% if perms.wiki.change_term %}<a href="{% url 'wiki-term-edit' term.id %}" class="btn btn-xs btn-default">Edit</a>{% endif %}
			</dt>
			<dd>{{ term.definition }}</dt>
		</div>
		{% endfor %}
	</dl>
	{% endfor %}
</div>
{% endblock content %}